### ISSUE TITLE
Migrations

### ISSUE THREAD

**Issue by sokil** [sokil/php-mongo#10]
- Create or delete indexes
- Create capped collections
- Insert new fields with default values to existed documents
- Remove fields
- Rename fields

**Comment by DanielRuf** [comment]
Hi, so far it seems there is no possibility to move / rename fields.
At least not with the current implementation.
I would have expected that we can use `get($fieldname)` to set the default if available.

**Comment by sokil** [comment]
you can always use native mongo's syntax: 

https://docs.mongodb.com/manual/reference/operator/update/rename/

```php
$collection->batchUpdate(
            [],
            [
                '$rename' => ['oldName' => 'newName'],
            ]
        );
```

**Comment by DanielRuf** [comment]
Could have been useful in the readme / examples. So far the readme does not cover this, just adding / unsetting fields. Also `get()` does not seem to be the same as in the parent class where it can be used to retrieve a field value.

**Comment by sokil** [comment]
> Also get() does not seem to be the same as in the parent class where it can be used to retrieve a field value.

`get ` not overloaded and present only in `Scructure`. I have add $default argument to it in master. Where get() does not seem to be the same as in the parent class?
