### ISSUE TITLE
Current implementation of ::aggegate vs actual driver's aggregate method

### ISSUE THREAD

**Issue by virtuman** [sokil/php-mongo#110]
We're currently experiencing an issue with excessive number of global locks and as I was doing the research on the subject I came across an interesting fact in the code.

Could someone clarify whether or not an current implementation of aggregate() in sokil similar to  mongo's driver aggregate function:
http://us2.php.net/manual/en/mongocollection.aggregate.php

Main question is whether or not the end result that is being passed to MONGO is the same query when it is passed via command() vs aggregate() because apparently command() might be causing global write locks in many conditions

Additionally, I could be very wrong, but on a driver side, it doesn't seem like it's possible to route the "command" queries to SECONDARY in the replicaset, I haven't checked the mongo driver code, but i would imagine that it only handles the type of commands (ie CRUD, aggregate, etc.) for decision making
and since "command" could really mean just about anything then anything in the "command" should be routed to primary?

Any suggestions and clarifications in this regard would be very helpful, thank you.

**Comment by sokil** [comment]
Aggragete method in mongo's coinsole is just a wrapper around command:

> db.phpmongo_test_collection.aggregate
```javascript
function (pipeline, extraOpts) {
   // ...
    var res = this.runCommand("aggregate", cmd);
   // ...
    return res;
}
```

PHP drivers `Collection::aggregate` also is just a wrapper around command:

https://github.com/mongodb/mongo-php-driver/blob/024c49c587e5b02d5375b9da2617c450fc5d6c3c/collection.c#L2608:L2613

```c
retval = php_mongo_runcommand(collection->link, &collection->read_pref, Z_STRVAL_P(db->name), Z_STRLEN_P(db->name), cmd, NULL, 0, &connection TSRMLS_CC);
	if (retval && php_mongo_trigger_error_on_command_failure(connection, retval TSRMLS_CC) == SUCCESS) {
		RETVAL_ZVAL(retval, 0, 1);
	}
```

**Comment by sokil** [comment]
But you can try to change db's read preferences to force reading from slaves:

https://github.com/sokil/php-mongo/blob/master/src/Database.php#L398:L431

**Comment by virtuman** [comment]
Thank you very much, after opening the ticket yesterday I looked into driver's code myself as well.
Shortly after posting this, I realized that there was a portion of our code that still used db.eval (php mongo ->execute(new \MongoCode($sQuery, [])); method). This method is marked as deprecated but I guess it still works and that's why we never replaced it with the aggregate wrapper.
Not only does this method get routed to PRIMARY, but this method puts a global write lock on the mongo server. 

Mongo manual says that it puts write lock for the time of query analysis but i have a suspicion that it might be putting global write locks for the duration of the call, because our average global wait time is well over 600 seconds (600,000 ms) and most of the longest queries run in under 30 seconds.

Thought I'd share my experience and recommend everyone to stay away from these types of calls.

**Comment by virtuman** [comment]
I also couldn't find setBatchSize or setCursos() method for the aggregate method, or actually i could figure out if there's a way to set any params on the aggregate operations other that through mapping definition, which in our case we don't really have and we do individual direct calls to the collections via php-mongo.

is there a way to specify any of these for large resultsets of aggregate() operations?
http://php.net/manual/en/mongocursor.batchsize.php
or does it not really apply anymore and large resultsets somehow get iterated within this aggregate module?

thank you.

**Comment by sokil** [comment]
Batch size supported in PHPMongo's cursor https://github.com/sokil/php-mongo/blob/master/src/Cursor.php#L321

But aggtregation cursor still not implemented, so for now there is no ability to change aggregation cursor params.

https://github.com/sokil/php-mongo/issues/111
