### ISSUE TITLE
Aggregate options

### ISSUE THREAD

**Issue by sokil** [sokil/php-mongo#114]
Refactoring aggregate options 

http://php.net/manual/ru/mongocollection.aggregate.php
https://docs.mongodb.org/manual/reference/command/aggregate/#dbcmd.aggregate
https://docs.mongodb.org/manual/reference/operator/aggregation-pipeline/

**Comment by atompulse** [comment]
Hi!
I wondered if you made any work related to this topic?
I have a situation:
Aggregate error: exception: Sort exceeded memory limit of 104857600 bytes, but did not opt in to external sorting. Aborting operation. Pass allowDiskUse:true to opt in
So according to:
https://docs.mongodb.org/manual/reference/method/db.collection.aggregate/#example-aggregate-method-external-sort
I will need to use allowDiskUse:true option when doing the aggregation...

Any ideas when this can be done?
Can I help?

**Comment by sokil** [comment]
Hi.

I'll try to implement this soon, you will be notified when i'll done.
Thank you.

**Comment by sokil** [comment]
Check out branch `aggregate`.
Now aggregation able to be configured:
```php
<?php
$collection
    ->createPipeline()
    ->match()
    ->group()
    ->allowDiskUse()
    ->setBatchSize(100)
    ->aggregate([...other_options...])
```

or even get cursor instead of array:
```php
<?php
$collection
    ->createPipeline()
    ->match()
    ->group()
    ->allowDiskUse()
    ->setBatchSize(100)
    ->aggregateCursor([...other_options...])
```

**Comment by atompulse** [comment]
Thanks man!
I tried it and looks like it's working!
You should consider merging this into master ;)

**Comment by sokil** [comment]
ok
