### ISSUE TITLE
Support Phongo (pecl/mongodb)

### ISSUE THREAD

**Issue by sraka1** [sokil/php-mongo#115]
As mentioned [here](https://jira.mongodb.org/browse/PHP-1472?focusedCommentId=1011817&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1011817) and [here](https://jira.mongodb.org/browse/PHPC-285), starting with PHP7, due to be released on [November 12th](https://wiki.php.net/todo/php70#timetable) the old pecl/mongo extension will not be supported. It's replacement will likely be the pecl/mongodb driver, codenamed [Phongo](http://mongodb-labs.github.io/mongo-php-driver-prototype/).

Seeing as PHP7 is dramatically faster than PHP5(.6), I think supporting the new driver as soon as possible would be a good idea. Not sure if it's better to create two versions/branches or to abstract all the driver API calls somewhere. In any case, the "php-mongo" API shouldn't need to change.

If I have any spare time, I might start with implementation myself.

**Comment by sraka1** [comment]
Also, the API docs [are already](http://php.net/manual/en/set.mongodb.php) on PHP.net.

**Comment by sokil** [comment]
i'm already thinking about that. will be glad for any help

**Comment by sraka1** [comment]
PHP 7.0.0 has been released; I think this should now be prioritised. 

I thought about writing a backwards-compatible layer for the new driver, but don't have much time nowadays. For the moment, I might just use https://github.com/mongofill/mongofill although performance will definitely suffer.

@sokil Thoughts?

**Comment by sokil** [comment]
Old pecl driver now legacy, so i see only one right way - replace it with phongo, because this extensions too differ to try use them both. Legacy extension works with collection and database objects, new extension is low lewel and want to implement database and collection objects in php side. Support of legacy extension will be moved to compatibility layer.

**Comment by sraka1** [comment]
@sokil Any new updates/plans for this? Can help if help is needed.

**Comment by sokil** [comment]
No updates and currently no plans. Sorry

**Comment by sokil** [comment]
Currently support of PHP 7 implemented in branch https://github.com/sokil/php-mongo/tree/php7-compat-layer. Solution based on https://github.com/alcaeus/mongo-php-adapter. After few test and improvements it will be released. I will be happy about performance reports and bugs in your code.

**Comment by sokil** [comment]
https://github.com/sokil/php-mongo/releases/tag/1.20
