### ISSUE TITLE
Bug with relations when documents pull disabled

### ISSUE THREAD

**Issue by Guuzen** [sokil/php-mongo#121]
If i try to disable documents pull i get error.
For example:
foreach ($client->getCollection()->disableDocumentPool()->find()->findAll() as $obj) {
  $relObj = $obj->getRelated("rel"); // returns nonexistent document
}
Error:
PHP Notice:  Undefined index: 56530d3c9716130b008b4567 in /var/www/html/vendor/sokil/php-mongo/src/Collection.php on line 501
getRelated trying to get document from pool when it's disabled.

**Comment by urixs** [comment]
For reproducing this bug, DocumentPool should be disabled for both collections.

```php
(new Obj1())->getCollection()->disableDocumentPool();
$objects2 = (new Obj2)->getCollection()->disableDocumentPool()
    ->find()
    ->limit(2)        // Collection should have minimum 2 documents
    ->findAll();
foreach ($objects2 as $obj2) {
    $obj1 = $obj2->getRelated("_Obj1");     // It's okay
}
foreach ($objects2 as $obj2) {
    $obj1 = $obj2->getRelated("_Obj1");     // It's error
}
```

Error
```
PHP Notice:  Undefined index: 5649e6255b77bf16008b4569 in /var/www/html/vendor/sokil/php-mongo/src/Collection.php on line 501
```

**Comment by sokil** [comment]
https://github.com/sokil/php-mongo/releases/tag/1.13.9

fixed
