### ISSUE TITLE
Unexpected expressions merge when 2 or more whereOr expressions in query builder

### ISSUE THREAD

**Issue by Guuzen** [sokil/php-mongo#126]
When i using 2 whereOr in query builder, condition merge in one "$or" element with 4 parameters when i expecting 2 "$and" elements with 2 "$or" elements inside each of them with 2 parameters each.  
Example:  
Documents in DB:  
```
{
   "id": "doc1",
   "field": 2,
   "field2": 4 
}  
{
   "id": "doc2",
   "field": 1,
   "field2": 3 
}  
{
   "id": "doc3",
   "field": 2,
   "field2": 5 
}
{
   "id": "doc4",
   "field": 1,
   "field2": 6 
}
```  
Query:  
```PHP
$firstExpression = (new \Sokil\Mongo\Expression())->where('field', 1);
$secondExpression = (new \Sokil\Mongo\Expression())->where('field', 2);
$thirdExpression = (new \Sokil\Mongo\Expression())->where('field2', 3);
$fourthExpression = (new \Sokil\Mongo\Expression())->where('field2', 4);
$cursor = $collection->find()
    ->whereOr($firstExpression, $secondExpression)
    ->whereOr($thirdExpression, $fourthExpression)
    ->findAll()
;
```  
Gives me all 4 documents, when i expecting AND between this 2 whereOr and doc1,doc2 as result.  
I can solve this problem by wrapping each WhereOr in WhereAnd:  
```PHP
$cursor = $collection->find()
    ->whereAnd(
        (new \Sokil\Mongo\Expression())->whereOr($firstExpression, $secondExpression)
    )
    ->whereAnd(
        (new \Sokil\Mongo\Expression())->whereOr($thirdExpression, $fourthExpression)
    )
    ->findAll()
;
```  
But it seems like tricky and not obvious because documentation says "All "where" conditions added with logical AND".

**Comment by sokil** [comment]
if we talk about logical operations line $or, or $and, they must be declared direclty. Notice about logical AND valid for all other where expressions, but $or and $and must be declared directly. $and may be omited if passed different expressions to same field:
https://docs.mongodb.com/manual/reference/operator/query/and/#and-queries-with-multiple-expressions-specifying-the-same-field
In your case $and must be specified to group same operations: https://docs.mongodb.com/manual/reference/operator/query/and/#and-queries-with-multiple-expressions-specifying-the-same-operator

So in your case 
```php
<?php
$cursor = $collection->find()
    ->whereAnd(
        (new \Sokil\Mongo\Expression())->whereOr($firstExpression, $secondExpression),
         (new \Sokil\Mongo\Expression())->whereOr($thirdExpression, $fourthExpression)
    )
    ->findAll();
```

**Comment by Guuzen** [comment]
didn't know about that, ty
