### ISSUE TITLE
Uncaught Error: Class '\MongoCollection' not found

### ISSUE THREAD

**Issue by zhaoxiong123** [sokil/php-mongo#167]
PHP Fatal error:  Uncaught Error: Class '\MongoCollection' not found

My php env is right , but the error always ~

**Comment by sokil** [comment]
Which PHP version do you use? What MondoDB extension do you use?

If you use  PHP >= 7.0 and https://pecl.php.net/package/mongodb as driver, you need to install compatibility layer:

```
composer require alcaeus/mongo-php-adapter
```

If you use PHP < 7.0 and https://pecl.php.net/package/mongo - show you steps to reproduce.

**Comment by zhaoxiong123** [comment]
oh, yes, i was fixed. thanks
