### ISSUE TITLE
Fulltext search

### ISSUE THREAD

**Issue by sokil** [sokil/php-mongo#37]
Full text search
http://docs.mongodb.org/manual/reference/operator/query/text

Ensure index
http://docs.mongodb.org/manual/core/index-text/

Allowed languages
http://docs.mongodb.org/manual/reference/text-search-languages/#text-search-languages

Command
http://docs.mongodb.org/manual/reference/command/text/#dbcmd.text

Define language
https://docs.mongodb.org/manual/tutorial/specify-language-for-text-index/

Sorting
https://docs.mongodb.org/manual/reference/operator/query/text/#text-operator-text-score

**Comment by dan-andreoli** [comment]
Hi Sokil,

there is any hack to implement or use this issue?

**Comment by sokil** [comment]
https://github.com/sokil/php-mongo#fulltext-search

Added in v.1.14

Feedback will be pleasant

**Comment by dan-andreoli** [comment]
Thanks, it works perfectly

**Comment by sokil** [comment]
nice)
