### ISSUE TITLE
Storing embedded documents

### ISSUE THREAD

**Issue by sokil** [sokil/php-mongo#66]
validation and setting embedded documents as `Structure` instances

- [ ] check old _data style
- [ ] `Subdocument` is a separate class with own getters and setters, extended from `Structure` or maybe new class `Subdocument`
- [ ] subdocument may be assigned to key of document or other subdocument
- [ ] subdocument data may be validated in its class
- [ ] subdocument may be get from document if mapping of field to document specified. Used `Structure::getObject` and `Structure::getObjectList`
- [ ] Subdocument transparently stored to db

**Comment by m7moud** [comment]
I just came here to ask the same question

**Comment by sokil** [comment]
### Storing embedded documents:

```php
<?php
//as array
$document->set('field', array(
    'subfied2' => 1,
    'subfied2' => 2,
));

// or same:
$document->set('field.subfied1', 1);
$document->set('field.subfied2', 2);

// as structure from 1.12.1
class SomeStruct extends \Sokil\Mongo\Structure
{
    public function setSome($value) { return $this->set('some', $value); }
}

$someStruct = new SomeStruct();
$someStruct->setSome(42);

$document->set('field', $someStruct);
```

Validating can be defied only in `Document` class, but plans to add ability of devining validation rules in Structure too:
```php
<?php

class Document
{
    public function rules()
    {
        return array(
            array('field.subfied1', 'email'),
        );
    }
}
```

### Storing list of embedded documents:
````php
<?php
// as array
$document->set('field', array(
    array(
        'subfied2' => 1,
        'subfied2' => 2,
    ),
    array(
        'subfied2' => 1,
        'subfied2' => 2,
    ),
));

// or through using `Document::push*()`:
$document->push('field', array(
    'subfied2' => 1,
    'subfied2' => 2,
));

// or structure
class SomeStruct extends \Sokil\Mongo\Structure
{
    public function setSome($value) { return $this->set('some', $value); }
}

$someStruct = new SomeStruct();
$someStruct->setSome(42);

$document->push('field', $someStruct);
```

Validating of embedded document list currently not supported

**Comment by sokil** [comment]
`Subdocument` is a separate class with own getters and setters, extended from `Structure` or maybe new lcass `Subdocument`

1) subdocument may be assigned to key of document or other subdocument
2) subdocument data may be validated in its class
3) subdocument may be get from document if mapping of field to document specified. Used `Structure::getObject` and `Structure::getObjectList`
4) Subdocument transparently stored to db

**Comment by m7moud** [comment]
Great, Thank you @sokil.

**Comment by sokil** [comment]
it's not implemented yet )
but i think i know hgow to implement it. 
wull be added soon

**Comment by m7moud** [comment]
I thought it is, I haven't tried it yet.

**Comment by sokil** [comment]
it's just a plan

**Comment by sokil** [comment]
done
