### ISSUE TITLE
Can I use behaviors with cursor ?

### ISSUE THREAD

**Issue by m7moud** [sokil/php-mongo#68]
I mean getting the behavior applied on all documents in cursor

**Comment by sokil** [comment]
I hope yes ) 

You can define them in mapping:
$database->map('collection', array(
    'behaviors' => array(...),
));

Or directly in custom document class by overriding `behaviors` method:
class SomeModel extends Document
{
    public function behaviors()
    {
        return array(....);
    }
}

Do you have any problems with them?

**Comment by m7moud** [comment]
I know that, but I should iterate on them and use the behavior with each one, I can't use it with a cursor.

exactly I want to apply a behavior that removes the password on findAll user

**Comment by sokil** [comment]
Yes, i found a bug. 

Fixed in release https://github.com/sokil/php-mongo/releases/tag/1.11.7

Thank you.
