### ISSUE TITLE
Optimize preparing data to store

### ISSUE THREAD

**Issue by sokil** [sokil/php-mongo#69]
data prepared or set if new and on operator with set on update

**Comment by m7moud** [comment]
again I'm here to ask about the same thing, in a scenario like this
->set('driving', ['license' => 1])
->set('driving.license', 1)

You end up getting: 'MongoWriteConcernException' with message .... Cannot update 'driving' and 'driving.license' at the same time

the operator holds two different set operation, and they are actually one, where do you think it should be handled? ``Operator``?

**Comment by sokil** [comment]
Bug reproduced. Wait for bugfix

**Comment by m7moud** [comment]
also the operators for
->set('name', 'Mahmoud'])
->unsetField('name'])

**Comment by sokil** [comment]
This case is normal. Why you unset field which you set right now? But mayme a'll add support of this.

But bug exists in all point-defined fields. There is no support of both definitions: through array and through point-defined string. Currently i'm trying to fix this.

**Comment by m7moud** [comment]
I'm still trying to figure the best practice for dynamic scheme with strict data types and variations.
currently I'm starting with assigning the whole payload to document and before validation, I do the re-structure and re-format the document.

**Comment by sokil** [comment]
```php
<?php

$document
->set('driving', ['license' => 1])
->set('driving.license', 1);
```

This is also not a bug.
For example you have this document:

```javascript
{driving: {license: 0, otherfield: "othervalue"}}
```

After `->set('driving', ['license' => 1])` you will get document:
```javascript
{driving: {license: 1}}
```

After `->set('driving.license', 1)` you will get document:

```javascript
{driving: {license: 1, otherfield: "othervalue"}}
```

So this two setters are not equal, do different things, and can't be executed together. Library doesn't detect this, but only database. Adding logic to detect this on library size will add unnecessary overhead and decrease performance.

**Comment by sokil** [comment]
Maybe to get strict data types you need to use validators or checks of data type in setters?

```php
<?php

class SomeDocument extends \Sokil\Mongo\Document
{
    public function rules()
    {
        return array(
            array('field', 'type', array('string', 'int')),
        );
    }

    public function setOtherField($value)
    {
        if(!is_numeric($value)) {
            throw new \InvalidArgumentException('Must be numeric');
        }

        $this->set('otherfield', $value);
    }
}
````

**Comment by m7moud** [comment]
I got a better idea of overriding the `set` and `createDocument` methods in my custom documents, `createDocument` will use `set`, and my set method will convert any arrays to dot notation two dimensional array before calling the parent `set`, and in that set method I will compare the field to the field type definition

**Comment by m7moud** [comment]
I'm looking also for away to implement STI or in here Single Collection Inheritance, my hopes isn't high on that, Ruby ODMs does that already, but I'm sticking to PHP.

**Comment by m7moud** [comment]
Doctrine too I guess

**Comment by sokil** [comment]
Something like STI already implemented through `Collection::getDocumentClassName(array $documentData = null)`:


```php
<?php

class MyCollection extends \Sokil\Mongo\Collection
{
    public function getDocumentClassName(array $documentData = null)
    {
        return '\MyClass' . ucfirst(strtolower($documentData['type']));
    }
}

Or by mapping:

```php
<?php
$database->map([
    'mycollection' => ['documentClass' => function($data) {
         return '\MyClass' . ucfirst(strtolower($data['type']));
    }],
]);
```

Did you mean something like that?

**Comment by sokil** [comment]
> I got a better idea of overriding the set and createDocument methods in my custom documents, createDocument will use set, and my set method will convert any arrays to dot notation two dimensional array before calling the parent set, and in that set method I will compare the field to the field type definition

I'm not shure this way has nice performance, if i understant you.

**Comment by m7moud** [comment]
Yeah I guess `DocumentClassName` will work Like STI, thank a lot.

and about the operators thing, there's a logic already to watch the `modifiedFields` and also the `Structure``set` method already do convert every dot notation fieldNames to an array. any of these could be reused.

**Comment by m7moud** [comment]
My implementation is something like this
```
class CustomDocument extends \Sokil\Mongo\Document {

    private $_dataTypes = [
        'name' => 'string',
        'birth_date' => '\MongoDate'
    ];

    public function set($fieldName, $value, $forceType = false) {
        if ($forceType && $this->_dataTypes[$fieldName]) {
            if (class_exists($this->_dataTypes[$fieldName])) {
                $value = new $this->_dataTypes[$fieldName]($value);
            } else {
                $value = settype($value, $this->_dataTypes[$fieldName]);
            }
        }
        return parent::set($fieldName, $value);
    }
```

**Comment by sokil** [comment]
You have broken polimorphism. Interface of your method is not compatible with super class, so if i will decide to add third argument, you will get error somewhere. If you need this, add custom method

```php
<?php

public function strictSet($fieldName, $value) {}

**Comment by m7moud** [comment]
createDocument will have to use that custom set too, I can use `strictSet` or I can make the overridden set takes two arguments and only check for `$this->_dataTypes[$fieldName]`
