### ISSUE TITLE
Relations - document object

### ISSUE THREAD

**Issue by bobbygrossmann** [sokil/php-mongo#73]
I don't know if this a problem but i cant get this right. 

Im doing a token collection "RELATION_BELONGS to UserCollection" but the object i'm getting back "$token->userRelations" returns  \Sokil\Mongo\Document Object and not \Models\UserDocument Object
So this results that i only can get _data but not any relation or relay the UserDocument object. "resolvedRelationIds" returns of course from Document Object and thats logic because it dosen't go inside the document object with relation().

**Comment by sokil** [comment]
Looks like a bug. I'll try to reproduce

**Comment by bobbygrossmann** [comment]
Good, its easy to reproduce. Create collection class and document class. Add relation to the document and try to catch the response in a controller with relation: tex $collection->bugResolved() :)

**Comment by sokil** [comment]
Can you show me your code? And what version of library do you use?

**Comment by bobbygrossmann** [comment]
i can see if i provide a exemple one other thing i dont understand, mixing _id and camelCase. Is it not better to keep everything snake_case inside a document parameter ? but still use camelCase inside php. I my old framwork i converted row document parameters snake_case to camelCase. For instance i use as you do with $_data for document structor. Any resan except little speed performance ?

Im cruise why mix $_data then i see you have mostly in psr-2 standards then it comes to method names and structor :) little confuse to mix :)

**Comment by sokil** [comment]
If you talk about underscore before methods and variables, this is my old habit and i am bringing code into accordance with coding standarts. So underscores in some methods and vars is just back comaribility.

**Comment by bobbygrossmann** [comment]
aha but collection use $_data everywhere. The only way i see quick is to do a abstract class to conver this for know or you have better idea ? any release date for new ? Or mayby edge releas version ?.

**Comment by bobbygrossmann** [comment]
I look closer i only need to inject data to constructor :) i need to try if i get same bug as before, i will get back to you tomorrow with my example

**Comment by bobbygrossmann** [comment]
Okej i'm almost there where i want but i think it the error is with createDocument method.

$collection->createDocument($data);  returns Sokil\Mongo\Document Object but that this to return the collections getDocumentClassName() :)

**Comment by bobbygrossmann** [comment]
So im trying again and my relation returns Sokil\Mongo\Document Object

**Comment by bobbygrossmann** [comment]
Okej here we have then, i'm copy case basic codes for this. Im using a abstract class to fix for $_data and general wrapper class:

AbstractCollection:
<?php

namespace Grossmann\Db;

use Sokil\Mongo\Collection;

abstract class AbstractCollection extends Collection
{
    public function __construct($database)
    {
        parent::__construct($database, static::$collectionName);
    }
}

AbstractDocument:
<?php

namespace Grossmann\Db;

use Sokil\Mongo\Document;
use Sokil\Mongo\Collection;

abstract class AbstractDocument extends Document
{
    public function __construct(Collection $collection, array $data = null)
    {
        $proporties = array_merge(static::$documentStructure, $data);

        parent::__construct($collection, $proporties);
    }
}


My token collection/document:
class AccessTokensCollection extends AbstractCollection
{
    /**
     * Collection name.
     * @var string
     */
    protected static $collectionName = 'oauth_access_tokens';

    /**
     * @param array $documentData
     * @return string
     */
    public function getDocumentClassName(array $documentData = null)
    {
        return '\Adela\Model\Oauth\AccessTokenDocument';
    }
}

class AccessTokenDocument extends AbstractDocument
{
    /**
     * Overridden database properties and their attributes.
     * @var array
     */
    protected static $documentStructure = [
        '_id' => null,
        'accessToken' => null,
        'clientId' => null,
        'expires'  => null,
        'userId'  => null,
        'scope' => null,
    ];

    /**
     * @return array
     */
    public function relations()
    {
        return ['userRelations' => [self::RELATION_BELONGS, 'users', 'userId']];
    }
}


This will return a AccessTokenDocument instance as i wanted. I inject this to a new service and after im doing this: $user = $token->userRelations;

This gives me return object as this:

Sokil\Mongo\Document Object
(
    [resolvedRelationIds:Sokil\Mongo\Document:private] => Array
        (
        )

    [collection:Sokil\Mongo\Document:private] => Sokil\Mongo\Collection Object
        (
            [_queryBuilderClass:protected] => \Sokil\Mongo\QueryBuilder
            [_queryExpressionClass:protected] => \Sokil\Mongo\Expression
            [documentClass:Sokil\Mongo\Collection:private] => \Sokil\Mongo\Document
            [_index:protected] => 
            [_database:protected] => Sokil\Mongo\Database Object
                (
                    [client:Sokil\Mongo\Database:private] => Sokil\Mongo\Client Object
                        (
                            [_dsn:Sokil\Mongo\Client:private] => mongodb://bobby:grossmann1989@127.0.0.1/
                            [_connectOptions:Sokil\Mongo\Client:private] => Array
                                (
                                )

                            [_mongoClient:Sokil\Mongo\Client:private] => MongoClient Object
                                (
                                    [connected] => 1
                                    [status] => 
                                    [server:protected] => 
                                    [persistent:protected] => 
                                )

                            [_databasePool:Sokil\Mongo\Client:private] => Array
                                (
                                    [grossdesk] => Sokil\Mongo\Database Object
 *RECURSION*
                                )

                            [_mapping:protected] => Array
                                (
                                )

                            [_logger:Sokil\Mongo\Client:private] => 
                            [_currentDatabaseName:Sokil\Mongo\Client:private] => 
                        )

                    [mongoDB:Sokil\Mongo\Database:private] => MongoDB Object
                        (
                            [w] => 1
                            [wtimeout] => 10000
                        )

                    [mapping:Sokil\Mongo\Database:private] => Array
                        (
                        )

                    [regexpMapping:Sokil\Mongo\Database:private] => Array
                        (
                        )

                    [classPrefix:Sokil\Mongo\Database:private] => 
                    [collectionPool:Sokil\Mongo\Database:private] => Array
                        (
                            [users] => Sokil\Mongo\Collection Object
 *RECURSION*
                        )

                    [collectionPoolEnabled:Sokil\Mongo\Database:private] => 1
                    [defultCollectionClass:Sokil\Mongo\Database:private] => \Sokil\Mongo\Collection
                    [defultGridFsClass:Sokil\Mongo\Database:private] => \Sokil\Mongo\GridFS
                )

            [_mongoCollection:protected] => MongoCollection Object
                (
                    [w] => 1
                    [wtimeout] => 10000
                )

            [documentPool:Sokil\Mongo\Collection:private] => Array
                (
                    [54d22574a4428ee154d63af1] => Sokil\Mongo\Document Object
 *RECURSION*
                )

            [isDocumentPoolEnabled:Sokil\Mongo\Collection:private] => 1
            [versioning:protected] => 
            [options:Sokil\Mongo\Collection:private] => Array
                (
                )

        )

    [_scenario:protected] => 
    [errors:Sokil\Mongo\Document:private] => Array
        (
        )

    [triggeredErrors:Sokil\Mongo\Document:private] => Array
        (
        )

    [eventDispatcher:Sokil\Mongo\Document:private] => Symfony\Component\EventDispatcher\EventDispatcher Object
        (
            [listeners:Symfony\Component\EventDispatcher\EventDispatcher:private] => Array
                (
                )

            [sorted:Symfony\Component\EventDispatcher\EventDispatcher:private] => Array
                (
                )

        )

    [operator:Sokil\Mongo\Document:private] => Sokil\Mongo\Operator Object
        (
            [_operators:Sokil\Mongo\Operator:private] => Array
                (
                )

        )

    [behaviors:Sokil\Mongo\Document:private] => Array
        (
        )

    [validatorNamespaces:Sokil\Mongo\Document:private] => Array
        (
            [0] => \Sokil\Mongo\Validator
        )

    [options:Sokil\Mongo\Document:private] => Array
        (
            [stored] => 1
            [versioning] => 
            [behaviors] => 
        )

    [_data:protected] => Array
        (
            [_id] => MongoId Object
                (
                    [$id] => 54d22574a4428ee154d63af1
                )

            [accountId] => MongoId Object
                (
                    [$id] => 54ce249aa4428e2002d63af1
                )

            [email] => info@grossmangroup.se
            [password] => $2y$12$EJGv2VWfhT89j2jmdRTtAOw21zFMc9WUxmKD8qF6X3NVABcrgGddS
            [passwordRecoveryToken] => 
            [passwordRecoveryExpiration] => 
            [created] => 
            [modified] => 
        )

    [_originalData:protected] => Array
        (
            [_id] => MongoId Object
                (
                    [$id] => 54d22574a4428ee154d63af1
                )

            [accountId] => MongoId Object
                (
                    [$id] => 54ce249aa4428e2002d63af1
                )

            [email] => info@grossmangroup.se
            [password] => $2y$12$EJGv2VWfhT89j2jmdRTtAOw21zFMc9WUxmKD8qF6X3NVABcrgGddS
            [passwordRecoveryToken] => 
            [passwordRecoveryExpiration] => 
            [created] => 
            [modified] => 
        )

    [_modifiedFields:protected] => Array
        (
        )

)

**Comment by bobbygrossmann** [comment]
If you cant read i can send you on email..

**Comment by sokil** [comment]
I think you use this library in wrong way. Can you show me a mapping of collections to collection classes? It seems that one collection don't now nothing about other collection and thats why it use default conficuration. You need to get all collection instances from one database instance and do not forget to map collection names to classes. 

```php
<?php

$client
    ->map([
        'somedb' => [
            'oauth_access_tokens' => '\Adela\Model\Oauth\AccessTokensCollection',
            'users' => '\UsersCollection'
        ]
    ]);

// now you can get tokens collection
$tokens = $client->getDatabase('somedb')->getCollection('oauth_access_tokens');
```

**Comment by bobbygrossmann** [comment]
Aha so i need to add to map pool everytime im doing a new collection. Okej then, i will try and reply.

**Comment by bobbygrossmann** [comment]
Thank it works.

**Comment by sokil** [comment]
Yes, and in most cases you even don't need to add classes, just regiser collection in map with required params like document class or query expression
