### ISSUE TITLE
collection getDistinct 

### ISSUE THREAD

**Issue by DanRec46** [sokil/php-mongo#74]
i've used $collection->getDistinct('fieldname'); ..... how to use distinct with where ?

$WHERE = function(\Sokil\Mongo\Expression $expression) {
        return $expression->where('HEADMONGO.DOCFLOW','ANA_ENTI');
        
        };
        
                
        //$objMongoCollection->find()->where('HEADMONGO.DOCFLOW','ANA_ENTI');
        
        $result = $objMongoCollection->getDistinct(
                                                    $strProperty,$WHERE
                                                   );
        
        return $result;

.....
Catchable fatal error: Argument 2 passed to Sokil\Mongo\Collection::getDistinct() must be an instance of Sokil\Mongo\Expression, instance of Closure given, called in /srv/www/vhosts/lasqualityweb/components/com_qualityweb/models/stores.php on line 413 and defined in /srv/www/vhosts/lasqualityweb/libraries/phpmongo/src/Collection.php

**Comment by sokil** [comment]
Method have accept only Expression object. Feature released in v.1.12.6. Not it accepts arrays and callables too.

Statement `return` not required in callable because expression already passed by reference.
