### ISSUE TITLE
Validator documentation issue

### ISSUE THREAD

**Issue by amit777** [sokil/php-mongo#78]
Hi, I've been experimenting with the project, and I noticed a potential small issue with the custom validator.

in the core code, you automatically append "Validator" to the classname.  So in the rules section you don't need to add _validator to custom validator classname.

eg, 

my_own_email   => MyOwnEmailValidator 

my_own_email_validator => MyOwnEmailValidatorValidator  (not intuitive).

sorry if I'm not being very clear on this.

**Comment by sokil** [comment]
You don't need to ad prefix. Logic my_own_email => MyOwnEmailValidator already working. Can you show me concrete code and your version of library tk reproduce?

**Comment by amit777** [comment]
Yes, this works. But I think the documentation indicates you should type
my_own_email_validator. In any case, I will make a pull request for some
minor documentation updates. Very nice package you have developed!

**Comment by sokil** [comment]
Glad you find it useful. Thanks for help.

**Comment by sokil** [comment]
I found in docs what do you talking about. Its a miss of documentation.
