### ISSUE TITLE
Logger levels - DEBUG, NOTICE, WARNING, ERROR

### ISSUE THREAD

**Issue by sokil** [sokil/php-mongo#90]

**Comment by ThomasBevolution** [comment]
Hi, i want to get the _id  after an update / upsert query, if the document not exists.
The Workaround Call is:
$db->lastError()
But lastError is not defined in Collection.php or Database.php

My Example:
Add Function in Collection.php

public function lastError() {
        return $this->_database->executeCommand(array('getlasterror' => 1));
}

http://php.net/manual/de/mongodb.lasterror.php

Is it possible to add this Function in future updates or is this the wrong way with LastError?

Thanks for your ODM , it is very helpful and easy to use

**Comment by sokil** [comment]
> Hi, i want to get the _id after an update / upsert query, if the document not exists.

If document not exists, what _id do you expect to see?

`Database::getLastError()` added in v.1.13.1

**Comment by ThomasBevolution** [comment]
Thanks i didn't saw the function.

I want to get the Object _id without new query findOne.
I work with MongoDB 2.4 and i want update a Document or insert if not exists with
update, upsert.
If updatedExisting => false, lastError returns $id (Object _id)
Output lastError:
{ ["updatedExisting"]=> bool(false) ["upserted"]=> object(MongoId)#13 (1) { ["$id"]=> string(24) "5554388269313c4a14c28a83" } ["n"]=> int(1) ["connectionId"]=> int(1234) ["err"]=> NULL ["ok"]=> float(1) }

**Comment by sokil** [comment]
You didn't saw it because i'v just add it :)

Check new version.
Thank you for using PHPMongo

**Comment by ThomasBevolution** [comment]
ahhh ok - thanks a lot ;)
