### ISSUE TITLE
Collection mapping names with underscore

### ISSUE THREAD

**Issue by brutto** [sokil/php-mongo#96]
Config client collections mapping with:
> client->map([
>                $database  => '\Some\Thing\Collection',
>            ]);

Then try to use:
>  $client->getCollection('some_name_with_underscore');

Finaly catch Exception like:
> Type: Sokil\Mongo\Exception
> Message: Class \Some\Thing\Collection\Some_name_with_underscore not found while map collection name to class
> File: ~\app\vendor\sokil\php-mongo\src\Database.php
> Line: 248

**Comment by brutto** [comment]
If i try to use simple collection names (without underscore) -- it looks like work properly.... (?!)

**Comment by brutto** [comment]
and yes, i use autoload

**Comment by brutto** [comment]
Thank's all. It's al about PSR-X =)

**Comment by sokil** [comment]
Раскажи детальней, что пошло не так. Композер не смог Some_name_with_underscore?
