### ISSUE TITLE
Cursor timeout

### ISSUE THREAD

**Issue by nerijunior** [sokil/php-mongo#98]
I'm trying to change the timeout at the cursor returned in collection but without success.

```php
$collection->find()->timeout(-1);
```

Thanks!

**Comment by sokil** [comment]
1) You can define client and server timeouts in mapping:
https://github.com/sokil/php-mongo#collection-definition-options

2) Also you can set timeouts directly to cursor:
https://github.com/sokil/php-mongo#query-timeouts
